// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package database

import (
	"context"
)

const countPendingJobs = `-- name: CountPendingJobs :one
SELECT count(*)::bigint FROM bca_email_jobs WHERE state IN ('queued','processing','retry_wait')
`

func (q *Queries) CountPendingJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingJobs)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const databaseReady = `-- name: DatabaseReady :one
SELECT EXISTS(SELECT 1 FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE c.relname='gmail_sync_operations' AND n.nspname='public' AND c.relkind='r') AS ready
`

func (q *Queries) DatabaseReady(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, databaseReady)
	var ready bool
	err := row.Scan(&ready)
	return ready, err
}
