// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthFlow struct {
	ID           pgtype.UUID
	Kind         string
	SecretHash   []byte
	Nonce        pgtype.Text
	PkceVerifier pgtype.Text
	UserID       pgtype.UUID
	ExpiresAt    pgtype.Timestamptz
	ConsumedAt   pgtype.Timestamptz
}

type BcaEmailJob struct {
	ID              pgtype.UUID
	IntegrationID   pgtype.UUID
	MessageID       string
	State           string
	Attempts        int32
	NextAttemptAt   pgtype.Timestamptz
	LeaseUntil      pgtype.Timestamptz
	ParserVersion   pgtype.Text
	ReasonCode      pgtype.Text
	EncryptedSource []byte
	DeliveryPayload []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type GmailIntegration struct {
	ID                    pgtype.UUID
	UserID                pgtype.UUID
	MailboxID             string
	EncryptedRefreshToken []byte
	KeyVersion            int16
	Status                string
	CreatedAt             pgtype.Timestamptz
}

type GmailSyncState struct {
	IntegrationID   pgtype.UUID
	HistoryID       pgtype.Text
	CoverageStart   pgtype.Timestamptz
	LastAttempt     pgtype.Timestamptz
	LastSuccess     pgtype.Timestamptz
	LeaseUntil      pgtype.Timestamptz
	LeaseGeneration int64
	RecoveryStatus  string
}

type OwnedAccount struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	Bank             string
	MatchToken       []byte
	MaskedIdentifier string
	Label            string
	CreatedAt        pgtype.Timestamptz
}

type Session struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	FamilyID    pgtype.UUID
	RefreshHash []byte
	ExpiresAt   pgtype.Timestamptz
	ConsumedAt  pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type Transaction struct {
	ID                       pgtype.UUID
	UserID                   pgtype.UUID
	IntegrationID            pgtype.UUID
	BankReference            string
	ReceiptKind              string
	Classification           string
	OccurredAt               pgtype.Timestamptz
	SourceLocalTime          string
	SourceTimezone           string
	AmountMinor              int64
	FeeMinor                 pgtype.Int8
	Currency                 string
	SourceAccountAlias       string
	BeneficiaryBank          pgtype.Text
	BeneficiaryAccountMasked string
	BeneficiaryMatchToken    []byte
	ParserVersion            string
	Note                     string
	Version                  int32
	CreatedAt                pgtype.Timestamptz
}

type TransactionAudit struct {
	ID            int64
	UserID        pgtype.UUID
	TransactionID pgtype.UUID
	Action        string
	BeforeValues  []byte
	AfterValues   []byte
	CreatedAt     pgtype.Timestamptz
}

type TransactionSource struct {
	TransactionID pgtype.UUID
	JobID         pgtype.UUID
}

type User struct {
	ID        pgtype.UUID
	GoogleSub string
	Email     string
	Timezone  string
	CreatedAt pgtype.Timestamptz
}
